import type { Metadata } from 'next';
import '@/style/globals.css';
import Toast from '@/components/common/Toast';
import Providers from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
        <Toast />
      </body>
    </html>
  );
}
